### ISSUE TITLE
Add cascade delete functionality to the cleaner

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#106]
We need to add functionality to allow `cascade delete` to the [FHIR resources cleaner](https://github.com/onaio/fhir-tooling/tree/main/cleaner)

This needs to be an optional flag `-cd --cascade-delete` which is false by default, and allows the user to automatically cascade delete linked/referenced resources

linked to: 
- https://github.com/onaio/fhir-tooling/issues/101
- cascade-delete is implemented in the [importer](https://github.com/onaio/fhir-tooling/tree/main/importer#9-delete-duplicate-practitioners-on-hapi) maybe a similar approach can be taken for this

**Comment by pld** [comment]
I thought the plan was to remove the cleaner entirely, and use the cleaning functionality in efsity?

**Comment by Wambere** [comment]
Leaving [this comment link](https://github.com/onaio/fhir-tooling/issues/101#issuecomment-1893980465) in response to the above just in case anyone is ever following up
