### ISSUE TITLE
Load test

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#139]
How long does the importer take to process/upload resources?

**Comment by Wambere** [comment]
WIP:

## Create
| Number of rows | First run | Second run | Average |
| :----:  |  ---:  |  ---:  |  ---:  |
| 10  | 3.047478 sec  | 2.146752 sec  |  2.597115 sec   |
| 50  | 3.213799 sec  | 3.012454 sec  |  3.1131265 sec |
| 100  | 5.043137 sec  |  3.587996 sec  |  4.3155665 sec  |
| 500  |  10.553804 sec   |  7.594241 sec   |  9.0740225 sec  |
| 1000  |     |     |      |
| 5000  |     |     |      |


## Update
| Number of rows | First run | Second run | Average |
| :----:  |  ---:  |  ---:  |  ---:  |
| 10  | 18.170744 sec  |  19.471326 sec  |  18.821035 sec   |
| 50  | 65.625331 sec  |  65.786284 sec  |  65.7058075 sec |
| 100  | 134.150385 sec  |  137.209854 sec   |  135.6801195 sec  |
| 500  |  685.372977 sec  |  662.525677 sec   |   673.949327 sec   |
| 1000  |     |     |      |
| 5000  |     |     |      |



## Delete & Expunge
| Number of rows | First run | Second run | Average |
| :----:  |  ---:  |  ---:  |  ---:  |
| 10  | 4.789495 sec  | 3.183279 sec   |  3.986387 sec   |
| 50  | 7.627782 sec  | 7.468043 sec   |  7.5479125 sec |
| 100  | 9.373147 sec  |  13.156831 sec   |  11.264989 sec   |
| 500  | 46.144737 sec  |  132.073351 sec   |  89.109044  sec  |
| 1000  |     |     |      |
| 5000  |     |     |      |

**Comment by pld** [comment]
Cool, can you move this into the readme or docs for importer? That can close this issue
