### ISSUE TITLE
Add support to generate test/dummy questionnaire responses

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#15]
**Overview**
Some projects have a lot of questionnaires, with this functionality it will be possible to quickly generate questionnaire responses which can be used to test the extraction of resources, validation of app configs etc

Currently this is done manually

We can use tools like [java-faker](https://github.com/DiUS/java-faker) or [datafaker](https://www.datafaker.net/) to help with the actual dummy data generation

The result needs to account for special cases like skip logic. For example if one question asks for the gender and there is a subsequent question that is only relevant to female responders, that answer should only be answered when expected.

We would also want to extract and validate the data after generation. For valiation we can ideally use the same implementation from [validate fhir resources](https://github.com/onaio/fhircore-tooling/issues/13)

**Implementation spec.**
Add a new sub command `generateResponses` to efcity

sample commands:
```
fct generateResponses -i /path/to/questionnaire 
```

**input** 
- The questionnaire resource
- Flag is `-i` and `--input` as an alias

**output**
- A valid questionnaire response resource

**Acceptance Criteria**

- [ ]  New sub command `generateResponses` added, taking in a path to a questionnaire resource
- [ ] Documentation for the command added to the README
- [ ] Extraction and validation of this newly generated questionnaire response
- [ ] Unit tests (_Framework and status checks to be set up*_)

Resources
- https://github.com/DiUS/java-faker
- https://www.datafaker.net/
- Resource validation: https://github.com/onaio/fhircore-tooling/issues/13

--------------------------------

**Comment by pld** [comment]
is this complete now?

**Comment by Wambere** [comment]
@pld not yet, I'll spare some time this week to see if I can close it out

**Comment by pld** [comment]
No worries, I certainly think [this](https://github.com/onaio/fhir-tooling/issues/199) is higher priority, I wasn't sure if this was left open by mistake because I thought I saw documentation that covered this feature when I was using the translation generation in fct
