### ISSUE TITLE
EUSM - Add support for importing jurisdictions

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#155]
Current jurisdiction structure from opensrp 1.0

From https://example.smartregister.org/opensrp/rest/location/getAll?includeInactive=true&is_jurisdiction=true&limit=10&return_geometry=true&serverVersion=100
```
{
    "type": "Feature",
    "id": "5fa61353-bbbb-4107-8c5f-79ce95839018",
    "properties": {
        "status": "Active",
        "parentId": "1fec2789-77aa-499d-a28f-fc9e6c354ea5",
        "name": "Sarobaratra Ifanja",
        "geographicLevel": 3,
        "version": 0
    },
    "serverVersion": 17964,
    "locationTags": [
        {
            "id": 4,
            "active": true,
            "name": "Commune",
            "description": "Commune Location Tag"
        }
    ]
}
```

**Comment by Wambere** [comment]
FHIR version

```
{
  "resourceType": "Location",
  "id": "5fa61353-bbbb-4107-8c5f-79ce95839018",
  "identifier": [
    {"use": "official", "value": "5fa61353-bbbb-4107-8c5f-79ce95839018"}
  ],
  "type": {
    "coding": [
      {
        "system" : "http://terminology.hl7.org/CodeSystem/v3-RoleCode",
        "code"   : "??"                                             ,
        "display": "??"
      }
    ]
  },
  "status": "active",
  "name": "Commune",
  "alias": ["??"],
  "description": "Commune Location Tag",
  "physicalType": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
        "code": "jdn",
        "display": "Jurisdiction"
      }
    ]
  },
  "partOf": {
    "reference": "Location/1fec2789-77aa-499d-a28f-fc9e6c354ea5",
    "display": "Sarobaratra Ifanja"
},
  "position": { ?? }
}
```

@dubdabasoduba  please assist in filling in the above

**Comment by Wambere** [comment]
Mapping to current [location csv](https://github.com/onaio/fhir-tooling/blob/main/importer/csv/locations/locations_full.csv)
[json payload ](https://github.com/onaio/fhir-tooling/blob/main/importer/json_payloads/locations_payload.json)this maps to for context 

| Column | Source |
| --- | --- |
| name | properties -> name | 
| status | properties -> status |
| method | "create" |
| id | id |
| parentName |  ?? |
| parentID | properties -> parentId |
| type | "Jurisdiction" |
| typeCode | "jdn" |
| physicalType | ?? |
| physicalTypeCode | ?? |


**Still missing** =  location tags

cc @dubdabasoduba @ageryck @AnnieMungai

**Comment by ageryck** [comment]
For location tags previously used for identifying location hierarchy are not a requirement in fhircore since we use the parent `partOf`, do we need import this or leave it out?

**Comment by ageryck** [comment]
`SELECT DISTINCT a.name, a.status, 'udpate' as method, a.geojson_id as id, (select b.name from core.location_metadata b where b.geojson_id=a.parent_id) as parentName, a.parent_id,
'Jurisdiction' as Type, 'jdn' as TypeCode, null as physicalType, null as physicalTypeCode from core.location_metadata a`

**Comment by ageryck** [comment]
tested okay
