### ISSUE TITLE
EUSM - Add support for users and teams

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#159]
Current structure from opensrp 1.0

From https://example.smartregister.org/opensrp/rest/practitioner

```
{
        "identifier": "7449181a-9472-eeaa-9b3c-e76d3de32d24",
        "active": true,
        "name": "John Doe",
        "userId": "2d43b35e-cece-4c81-a5f4-3132a808463d",
        "username": "johnD",
        "dateCreated": "2022-11-17T05:40:10.538Z",
        "dateEdited": "2022-12-08T08:03:43.801Z",
        "serverVersion": 33
}
```

From https://example.smartregister.org/opensrp/rest/practitionerRole

```
{
        "identifier": "335e4285-b98c-4506-93b4-4a2f5f0ed147",
        "active": true,
        "organization": "578c4814-ca77-4e1a-b8a1-b734e0b8c3ed",
        "practitioner": "7449181a-9472-eeaa-9b3c-e76d3de32d24",
        "code": {
            "text": "Community Health Worker"
        }
}
```

I couldn't get any users from https://example.smartregister.org/opensrp/rest/user?page_size=10&source=OpenMRS&start_index=0

```
{
    "message": "The server encountered an error processing the request.",
    "status": "500 INTERNAL_SERVER_ERROR",
    "data": null,
    "success": false
}
```

**Comment by Wambere** [comment]
FHIR version

```
{
  "resourceType": "Practitioner",
  "id": "7449181a-9472-eeaa-9b3c-e76d3de32d24",
  "identifier": [
    {
      "use": "official",
      "value": "7449181a-9472-eeaa-9b3c-e76d3de32d24"
    },
    {
      "use": "secondary",
      "type": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/identifier-type",
            "code": "KUID",
            "display": "Keycloak user ID"
          }
        ],
        "text": "Keycloak user ID"
      },
      "value": "2d43b35e-cece-4c81-a5f4-3132a808463d"
    }
  ],
  "active": true,
  "name": [
    {
      "use": "official",
      "family": "Doe",
      "given": [
        "John",
        "N"
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "800-651-2242",
      "use": "home"
    },
    {
      "system": "email",
      "value": "john.doe@example.com"
    }
  ],
  "address": [
    {
      "use": "home",
      "line": [
        "27 South Ave"
      ],
      "city": "Tulsa",
      "state": "OK",
      "postalCode": "74126",
      "country": "USA"
    }
  ],
  "gender": "male"
}
```


```
{
  "resource": {
    "resourceType": "PractitionerRole",
    "id": "430",
    "active": true,
    "practitioner": {
      "reference": "Practitioner/7449181a-9472-eeaa-9b3c-e76d3de32d24",
      "display": "John Doe"
    },
    "organization": {
      "reference": "Organization/578c4814-ca77-4e1a-b8a1-b734e0b8c3ed",
      "display": "Team A"
    },
    "code": [
      {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/practitioner-role",
            "display": "Community Health Worker"
          }
        ]
      }
    ]
  }
}
```

@dubdabasoduba  please assist with filling in the above

**Comment by Wambere** [comment]
After a meeting discussion we realized that we do not need to do this any more, we can just map the opensrp 1.0 data into the already existing user creation csv [here](https://github.com/onaio/fhir-tooling/blob/main/importer/csv/users.csv)

**Comment by Wambere** [comment]
Mapping to current [location csv](https://github.com/onaio/fhir-tooling/blob/main/importer/csv/users.csv)
[json payload ](https://github.com/onaio/fhir-tooling/blob/main/importer/json_payloads/user_resources_payload.json)this maps to for context 

| Column | Source |
| --- | --- |
| FirstName | ?? |
| LastName | ?? |
| Username | ?? |
| Email | ?? |
| id | ?? |
| UserType | ?? | 
| EnableUser | ?? |
| KeycloakGroupID | ?? |
| KeycloakGroupName | ?? |
| ApplicationID | ?? |
| Password | ?? |

Leaving these all empty because I think it makes sense to pull from the users endpoint instead of the practitioners if this information is available there. So pending until we can get data from there

cc @dubdabasoduba @ageryck @AnnieMungai

**Comment by Wambere** [comment]
@ageryck good catch 👍🏾 

Where should we apply this change? Practitioner, Practitioner Role, Group, or all three?

**Comment by ageryck** [comment]
> @ageryck good catch 👍🏾
> 
> Where should we apply this change? Practitioner, Practitioner Role, Group, or all three?

I want to say all three however I need @peterMuriuki  to confirm web client behavior that will be used to manage these after import if re-activating the practitioner re-activates all of the other resources.

**Comment by peterMuriuki** [comment]
a change in the active status of a keycloak user is synced to the associated fhir resources:  Group, practitioner, and practitionerRole.

**Comment by ageryck** [comment]
tested ok
