### ISSUE TITLE
Remove csvs for users to careTeam assignment and careteam to org assignments

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#165]
- [x] remove users to careteam assignment
- [x] remove careteam to org assignment
- [x] add test to assign users to careteams using the careteam_full csv
- [x] add test to update the assignment of users to careteams using the careteam_full csv
- [x] add test to remove the assignment of users to careteams using the careteam_full csv
- [x] add test to assign careteams to orgs using the careteam_full csv
- [x] add test to update the assignment of careteams to orgs using the careteam_full csv
- [x] add test to remove the assignment of careteams to org using the careteam_full csv
- [x] update documentation for all the above

note: this is to ensure that tooling works the same way that the web works

**Comment by Wambere** [comment]
We have taken a closer look at this and think that it makes more sense to use the [careTeam_full](https://github.com/onaio/fhir-tooling/blob/main/importer/csv/careteams/careteam_full.csv) csv to do both assignments of users to careTeams and careTeams to Organizations. Does both assignments in one go, and is cleaner, no possibilities of duplicate assignments etc

So switching this issue to remove the two options for assigning users to careteams and careteams to orgs, and changing the docs to all point to updating the careTeam resource for those assignments

**Comment by joyce-x-chen** [comment]
Hi @Wambere thanks for this initiative. I 100% agree with the approach to simplify the number of steps involved in creating and assigning users/careteams/orgs/locations. 

I understand that your proposal is based on the current implementation in FHIR Web, but I'd like to suggest the reverse process and instead assign users to careteams and orgs using the users.csv. Centering the user is a more natural way to think about assignments than centering the group and thinking of which users belong to it.

Just as an example, it's much easier for me to think about an Ona employee and identify which team they belong to, vs. thinking about a team and try to recall every employee that belongs to that team. 

Hope that makes sense - just a suggestion for your consideration.

**Comment by Wambere** [comment]
@joyce-x-chen that's a great idea! I'll look into it more and see if we can raise a separate issue for it
