### ISSUE TITLE
Standardization of labels for bulk import CSVs

### ISSUE THREAD

**Issue by joyce-x-chen** [onaio/fhir-tooling#171]
It would be great if we could standardize the naming and capitalization of labels (column names in row 1) across the [bulk import CSVs](https://github.com/onaio/fhir-tooling/tree/main/importer/csv) to avoid confusion and minimize errors. I also have _questions_ about a few columns that have an unclear use/purpose. 

### locations_min.csv
- name > `locationName`
- status > `locationStatus`

### locations_full.csv
- name > `locationName`
- status > `locationStatus` (https://hl7.org/fhir/R4B/valueset-location-status.html)
- method
- id > `locationId`
- parentName > `locationParentName`
- parentID > `locationParentId`
- type > `locationType` - _I think we can drop this and only use locationTypeCode_
- typeCode > `locationTypeCode`
- physicalType > `locationPhysicalType` - _I think we can drop this and only use physicalTypeCode_
- physicalTypeCode > `locationPhysicalTypeCode`
- longitude
- latitude 
_Why do we have both type and physicalType now? In what context would they be different? I see that there is a distinct [serviceDeliveryLocationRoleType](https://terminology.hl7.org/3.1.0/ValueSet-v3-ServiceDeliveryLocationRoleType.html) in the FHIR specs, but I believe physicalType should meet most (if not all) of the use cases for OpenSRP...at least the use cases we would want to support cc: @dubdabasoduba in case physicalType was recently added for EUSM_

### users.csv
- FirstName > `firstName`
- LastName > `lastName`
- Username > `username`
- Email > `email`
- id > `userId`
- UserType > `userType`
- EnableUser > `enableUser`
- KeycloakGroupID > `keycloakGroupId`
- KeycloakGroupName > `keycloakGroupName`
- ApplicationID > `appId`
- Password > `password`

### organizations_min.csv
_Should we keep this template? I recommend removing this option and requiring the organizations_full.csv template to be provided, especially since each org needs a uuid_

### organizations_full.csv
- name > `orgName`
- active > `orgActive` (https://hl7.org/fhir/R4B/organization-definitions.html#Organization.active)
- method
- id > `orgId`
- identifier - _What is this used for? Could we remove this?_
- alias - _What is this used for? Could we remove this?_

### organization_locations.csv > `organizations_locations.csv`
- orgName
- orgID > `orgId`
- locationName
- locationID > `locationId`

### practitioner_organization.csv > `users_organizations.csv`
- practitionerId > `userId`
- practitionerName > `username`
- orgId 
- orgName 
_Please switch the orders of username and userId so that username comes first, same with orgName and orgId. It makes it easier to use VLOOKUP to find the corresponding userId and orgId._
_Note that one user may be assigned to multiple orgs (though this needs to be evaluated further for potential implications). Based on the template, it seems that the way to assign a user to multiple orgs is to create multiple rows for each org assignment. This is fine, but note that it is different from how the careteams_full.csv approaches it._ 

### careteam_min.csv 
_Should we keep this template? I recommend removing this option and requiring the careteam_full.csv template to be provided, especially since each careteam needs a uuid_

### careteam_full.csv > `careteams_full.csv`
- name > `careTeamName`
- status > `careTeamStatus` (https://www.hl7.org/fhir/r4b/valueset-care-team-status.html)
- method
- id > `careTeamId`
- identifier - _What is this used for? Could we remove this?_
- organizations - `orgId` - _Please confirm that the orgId is used for assigning careTeams to managing organizations in this csv_
- participants - `userId` - _Please confirm that the userId is used for assigning users to careTeams in this csv_
_It could be quite hard for someone to include multiple orgIds and multiple userIds in a single column without introducing errors. It may be preferable to restrict those columns to a single entry, and instead require duplication of the careTeam in multiple rows. However, this change may not be necessary in the long run if we shift towards a user-centric approach._

### users_careteam.csv
_Skipping this based on plans to remove this template as described in issue #165_

### careteam_organizations.csv
_Skipping this based on plans to remove this template as described in issue #165_

**Comment by dubdabasoduba** [comment]
> Why do we have both type and physicalType now? In what context would they be different? I see that there is a distinct [serviceDeliveryLocationRoleType](https://terminology.hl7.org/3.1.0/ValueSet-v3-ServiceDeliveryLocationRoleType.html) in the FHIR specs, but I believe physicalType should meet most (if not all) of the use cases for OpenSRP...at least the use cases we would want to support cc: @dubdabasoduba in case physicalType was recently added for EUSM

- OpenSRP web uses physicalType to differentiate what locations are shown on the Location Hierarchy (Jurisdiction) and which ones are shown on the list of Jurisdiction children i.e. points e.g. buildings, service points etc
- Since FHIR R4B does not allow search by physicalType, we opted to add the same code in physicalType in the type property. This helps us search on the API and the mobile app
- Type can be used for multiple uses one of the use cases that will be added soon is the ability to record Location Geographical Levels.
    -  This will help the Analytics team when creating hierarchies for filtering.It will also help the content authors who need to load hierarchies on the questionnaires.
    - This will be added as a mandatory code for all our apps.  OpenSRP web will automatically generate the levels. We will also need to add this to the bulk upload tool
- Other projects might use the type field to add metadata to the locations e.g. describing the donors involved in that location

**Comment by dubdabasoduba** [comment]
> - type > locationType - I think we can drop this and only use locationTypeCode
> - physicalType > locationPhysicalType - I think we can drop this and only use physicalTypeCode

@joyce-x-chen FHIR CodeSytems have several properties. The 3 most used ones are `system`, `code` and `Display`
The column `locationType` holds the `Display` and `locationTypeCode` holds the `code` 

- The display is human-readable and understandable. It provides an easy way for humans to interpret the resources and know what the codes stand for.

**Comment by dubdabasoduba** [comment]
> identifier - What is this used for? Could we remove this?
> alias - What is this used for? Could we remove this?

@joyce-x-chen We use `identifier` for interoperability purposes, mostly IDs from other systems would be linked here.  They also provide an alternative way to search for our data in case IDs can't be accessed. Different FHIR servers will generate FHIR resource IDs differently, having the `identifier` will mean we can still find "our" resources if we have to share data with other servers. 

- I am okay with removing the `alias` cc: @Wambere

**Comment by Wambere** [comment]
@joyce-x-chen the min csvs are useful for dev testing mostly, sometimes we need to test something fast and just need the minimum required fields, so I'd recommend we keep those. Users can still use the full csvs for their uploads

> organizations - orgId - Please confirm that the orgId is used for assigning careTeams to managing organizations in this csv participants - userId - Please confirm that the userId is used for assigning users to careTeams in this csv It could be quite hard for someone to include multiple orgIds and multiple userIds in a single column without introducing errors. It may be preferable to restrict those columns to a single entry, and instead require duplication of the careTeam in multiple rows. However, this change may not be necessary in the long run if we shift towards a user-centric approach.

I confirm that the above two columns are used for careTeam assignment to orgs and participants. And yes, we are looking into a more user-centric approach
