### ISSUE TITLE
Add an Administrative level for each Location

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#172]
### Issue Context?
- We would like to introduce the concept of an administrative level for each location in the hierarchy. 
- The Root location would always have level `0` then all the children would have level `parent_level + 1` 

### Issue Implementation details?

- [ ] Add an administrative level for every location resource. If a location does not have a parent selected then the administrative level will be `0`. All the children in the hierarchy will have an administrative level of `parent_level + 1` 
- [ ] This level is to be added to the `type` property of the Location resource and should have the following properties
```json
 {
    "system" : "https://smartregister.org/codes/administrative-level",
    "code"   : "0"                                                   ,
    "display": "Level 0"
  }
```

### Issue Acceptance criteria?

- [ ] All Locations created by the bulk upload tool should automatically have an administrative level added to them. 

### Relevant Information

**Sample Codes**
```json
[
  {
    "system" : "https://smartregister.org/codes/administrative-level",
    "code"   : "0"                                                   ,
    "display": "Level 0"
  },
  {
    "system" : "https://smartregister.org/codes/administrative-level",
    "code"   : "1"                                                   ,
    "display": "Level 1"
  }
]
```

**Comment by Wambere** [comment]
@dubdabasoduba thinking it might make sense to add an optional column in the csv for this value as well, such that if the value is in the csv we use it and if not we pull it from the parent location endpoint. Just being cautious of how much more time it will take to load locations if we always have to hit the parent endpoint

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba thinking it might make sense to add an optional column in the csv for this value as well, such that if the value is in the csv we use it and if not we pull it from the parent location endpoint. Just being cautious of how much more time it will take to load locations if we always have to hit the parent endpoint

@TraciebelWairimu and I had a chat about this today. @Wambere  I agree with you the column on the CSV would be the easiest way to build this.  

We might need to add some validation on the tools to make sure the levels are added correctly.  This is meant to validate the user entry
