### ISSUE TITLE
[Bug Report] Roll back the interpolation on the configs if the translations fails

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#197]
## Context
- The translation string extraction replaces the human-readable strings with interpolated strings that look something like this `{{ 3e7ecdffb97d880057b6c9463f1ff985 }}`
- It then moves the human-readable strings to the translation files which are `.properties` 
- If the translation string extraction process fails the config files remain with interpolated strings but the corresponding human-readable strings are not added to the translation files
- This makes it difficult to display the human-readable strings on the app correctly. 
- We would like to update the tooling to rollback to the correct last state in case the translation strings extract fails.

## Acceptance criteria
- [ ] Correctly extract strings from the configs and add them to the translation files
- [ ] Rollback the interpolations on the configs incase the translation strings fails

**Comment by ageryck** [comment]
We can approach this by creating a temp backup folder of the target directories and then running the extraction/interpolation. If it runs successfully then delete the temp backup folder else if there's an exception then you can use the backup to replace the half-processed files.
