### ISSUE TITLE
[Enhancement] Could we generate all the translations in the same file

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#198]
## Context
- The translation string extraction process happens for both the configs and questionnaires. 
- Each submodule i.e. configs and questionnaires generates its translation folder and file.  
- I would recommend we have one translation folder and file for both modules.  
    - This would make it easier to update transifex for the client teams

## Acceptance Criteria
- [ ] Update the tooling to generate 1 translation folder and file. We can have the folder and file in the configs module

**Comment by ndegwamartin** [comment]
@dubdabasoduba could you add some more details for this?

**Comment by ndegwamartin** [comment]
Not sure if this solves it but it is worth noting that for the translation command one of the flags/options supported is the destination file for the translations. [See here](https://github.com/onaio/fhir-tooling/tree/main/efsity#localization)

Perhaps the change needed is to have it support the destination as a Folder as well cc @dubdabasoduba @lincmba

**Comment by ageryck** [comment]
@hilpitome Let's target to write the same file at once with all the text/label extractions from both configs and questionnaires, if we experience any challenges executing this at once then we may target the same destination folder with multiple files.
