### ISSUE TITLE
Update the translation tooling to extract missed text propoerties

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#207]
## Context
- The efsity tooling extract text from predefined `properties` on the fhircore configs
- Due to updates and the introduction of new configs some to the text properties are now not being translated
- Update the efsity tooling to extract and interpolate all the text from the configs

## Implementation
- [x] Add the following text properties to the translation extraction
    - [x] [secondaryText](https://github.com/onaio/fhir-resources/blob/e229614704ee0098994511edf28f849045ebfd39/eusm/configs/profiles/service_point_profile_config.json#L809) 
    - [x] [primaryText](https://github.com/onaio/fhir-resources/blob/1d0d8a0a7720e0c06acc77bfd39080e19c6c9ae4/eusm/configs/profiles/service_point_profile_config.json#L555)

**Comment by ndegwamartin** [comment]
`primaryText` is not supported as well
