### ISSUE TITLE
Request of importer module  code walkthrough

### ISSUE THREAD

**Issue by hilpitome** [onaio/fhir-tooling#212]
We are requesting a code walkthrough of the [importer](https://github.com/onaio/fhir-tooling/tree/main/importer) module to facilitate the implementation of [Multi-Factor Authentication (MFA) for privileged users, such as frontend web admins](https://github.com/onaio/opensrp-tasks/issues/189) OpenSRP roadmap. cc @Lentumunai-Mark

**Comment by Wambere** [comment]
This happened on last week
