### ISSUE TITLE
[Importer] Add the ability to define the `system` URL for Location types

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#235]
### Context
- The `system` URL defined [here](https://github.com/onaio/fhir-tooling/blob/a4a141675ae09bce9695a080290c5dc52ce14e05/importer/json_payloads/locations_payload.json#L26) is what the FHIR spec uses for the FHIR location types. 
- Different Implementations might have different `system` URLs e.g EUSM will use `http://smartregister.org/CodeSystem/eusm-service-point-type` as defined on the CodeSsytems [here](https://github.com/onaio/fhir-resources/blob/a0b55d8f806e94027b4c6b8c87b56173280a8c7c/eusm/fhir_content/codeSystem/service_point_type.json#L4)
- Let's update [this](https://github.com/onaio/fhir-tooling/blob/a4a141675ae09bce9695a080290c5dc52ce14e05/importer/json_payloads/locations_payload.json#L26) and the Location Template to allow the provision of the URL. 
- We can use the default FHIR URL if one is not provided 

### Implementation
- [ ] Allow the provision of custom `system` URLs for the Locations

**Comment by Wambere** [comment]
@dubdabasoduba the initial thought was that any of the system urls (more than for locations) might need to change based on the project/implementation (maybe even the whole json object sometimes?), and that these would just be changed on the json payloads when working with the different projects to avoid the the configuration and implementation being too long and maybe confusing. So kind of thinking of the json payloads as "part of" the configuration. 

Does this approach make sense? or do we need to restrategize on making all of these configurable?

**Comment by dubdabasoduba** [comment]
@Wambere While this makes sense, I am not sure how it would work with the OpenSRP web bulk upload functionality. If we can figure that out then this would be the best approach

**Comment by Mstjamush** [comment]
**Issues**

1. Location upload - Upload shows to be successful but location is available on Web
2. Organization-Location assignment is not happening (Could be because of Location upload issue)
3. Product upload is failing. (reference the screen shot attached)

![Image](https://github.com/user-attachments/assets/c6d892b8-12e4-47c6-8913-e4c1b7e3200e)
