### ISSUE TITLE
[Importer] Add an "main" List to Inventory Import function 

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#236]
### Context
- The OpenSRP mobile application uses Lists to download data created by the OpenSRP web client.
- The current Inventory functionality works as follows:
	1. Create a Group resource that holds the inventory information and links to the product.
	2. Create a List resource to link the Inventory to the Location.
	3. The above List and Group resources are then referenced by another List resource, which is referenced in the composition resource in the mobile application configurations.
- This ticket adds the ability to update/create the “3rd” list. This can be achieved as follows:
    - When importing inventories, the user can provide a List ID to fetch the List where the Group (step 1) and List (step 2) references will be added.
    - If the ID is provided and the List does not exist on the server, then create a List with the same ID.
    - If a user does not provide the ID, then create a new List with an autogenerated ID.

### Implementation
- [ ] Allow users to provide the List ID to be used to reference Group (1 above) and List (2 above)
- [ ] Create a List based on the provided ID or an autogenerated one
- [ ] Link the Group (1 above) and List (2 above) to this newly created list

### Sample resource
```json
{
  "resourceType": "List",
  "id": "90e91971-6a46-4948-9543-f5efb6aa48df",
  "meta": {
    "versionId"  : "46"                           ,
    "lastUpdated": "2024-07-23T15:44:51.960+00:00",
    "source"     : "#926537bcaddf3311"
  },
  "identifier": [
    {"use": "official", "value": "90e91971-6a46-4948-9543-f5efb6aa48df"}
  ],
  "status": "current",
  "mode": "working",
  "title": "Supply Chain commodities",
  "code": {
    "coding": [
      {
        "system" : "http://smartregister.org/codes",
        "code"   : "22138876"                      ,
        "display": "Supply Inventory List"
      }
    ],
    "text": "Supply Inventory List"
  },
  "entry": [
    { "item": {"reference": "Group/40e56225-afc6-484d-8b49-30d943df26c9"} },
    { "item": {"reference": "List/ae7ef0ae-82de-4144-9c5d-b090d85e8153" } }
  ]
}
```

**Comment by Mstjamush** [comment]
**Issues**

1. Location upload - Upload shows to be successful but location is available on Web
2. Organization-Location assignment is not happening (Could be because of Location upload issue)
3. Product upload is failing. (reference the screen shot attached)
