### ISSUE TITLE
Fix 400 Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#247]
When trying to create users or set up Keycloak roles using keycloak, you get the following 400 error

<html>

<head>
	<title>400 Request Header Or Cookie Too Large</title>
</head>

<body>
	<center>
		<h1>400 Bad Request</h1>
	</center>
	<center>Request Header Or Cookie Too Large</center>
	<hr>
	<center>nginx</center>
</body>

</html>

**Comment by Wambere** [comment]
Initial investigation by @peterMuriuki 
>Looked into this and I think the problem lies at the keycloak level, where the tokens generated for some of the users is too huge for the configured header size for the respective keycloak deployment instance. After checking on keycloak I can confirm there is a lot of claims that are added to the access token which bloats up the token size. A user with a lot of role assignment will most likely have a token whose size is huge and will have all requests to keycloak fail with the 400 Request Header too large

>possible solutions:
>- We can increase the max-header size on keycloaks nginx configs
>- Review claims added to the tokens, it looks like roles are mapped twice.

**Comment by bennsimon** [comment]
@Wambere Which keycloak instance is being referred to here (kindly share the url)? Are the requests made directly to keycloak?

**Comment by Wambere** [comment]
@bennsimon keycloak-stage, and yes, requests are made directly. An example request url  `https://keycloak-stage.smartregister.org/auth/admin/realms/FHIR_Android/users?exact=true&username=janey`

**Comment by bennsimon** [comment]
@Wambere Could you re-try the same request?

**Comment by Wambere** [comment]
@bennsimon it works, thank you!
