### ISSUE TITLE
Remove accountability end date in inventory template

### ISSUE THREAD

**Issue by peterMuriuki** [onaio/fhir-tooling#264]
In the inventory template -> the accountability end date can be computed from the products' accountability period, and thus be removed from the template or made optional
- Update date fields such that one can provide a date instead of datetime i.e. without the time and timezone information.

**Comment by Wambere** [comment]
@peterMuriuki the initial understanding was that this importing is from the system and these values have already been calculated and are available there. I'm assuming the case you are referring to is new products?
I'm okay with making the column optional, and automatically calculating if the field is empty

The `accountabilityPeriod` according to our sample csv is an integer field, e.g 12. So does this mean that the accountability end date should be calculated by simply adding the 12 days to the inventory delivery date?
