### ISSUE TITLE
Enhancement to support validation via CI

### ISSUE THREAD

**Issue by ndegwamartin** [onaio/fhir-tooling#305]
A follow up task to issue https://github.com/onaio/fhir-tooling/issues/199 based on the comment here https://github.com/onaio/fhir-tooling/pull/281#issuecomment-2429450135

As part of validation efsity tries to connect to the FHIR Base URL server defined for the `QuestionnaireResponse` generated here for validation - https://github.com/onaio/fhir-tooling/blob/199-validate-sm/efsity/src/main/java/org/smartregister/command/ValidateStructureMapCommand.java#L106-L115 leading to the exception here :

![Screenshot 2024-10-17 at 19 10 03](https://github.com/user-attachments/assets/3078fc56-e2b5-4a77-81ab-b6338f190410)

This can be reproduced by running the structure map validation command e.g. via command line to validate.

**Comment by ndegwamartin** [comment]
Did some investigating, this is the block of code that does the the server POST request - https://github.com/onaio/fhir-tooling/blob/main/efsity/src/main/java/org/smartregister/command/QuestionnaireResponseGeneratorCommand.java#L182-L185

Do we need to perform a server submission when doing validation?

**Comment by Wambere** [comment]
Hey @ndegwamartin, yes we do
The way we are validating the structureMap is using the questionnaire. We use the questionnaire to generate a questionnaireResponse which we then use to extract resources and confirm that all that was expected from the structureMap is actually created, and valid. 
Using the populate mode, the way the questionnaireResponse is generated is by hiting the `/$poulate` endpoint on the questionnaire. So the questionnaire has to exist first before we can generate a questionnaireResponse from it.
The ai mode does not require a server but it also unfortunately does not always generate valid resources (compared to the populate mode)

The idea for CI was to just have a job that starts up the FHIR server which can be used for the process. An alternative would be to deploy a server just for this that the CI can connect to... depending on whichever makes more sense

**Comment by ndegwamartin** [comment]
> Hey @ndegwamartin, yes we do The way we are validating the structureMap is using the questionnaire. We use the questionnaire to generate a questionnaireResponse which we then use to extract resources and confirm that all that was expected from the structureMap is actually created, and valid. Using the populate mode, the way the questionnaireResponse is generated is by hiting the `/$populate` endpoint on the questionnaire. So the questionnaire has to exist first before we can generate a questionnaireResponse from it. The ai mode does not require a server but it also unfortunately does not always generate valid resources (compared to the populate mode)
> 
> The idea for CI was to just have a job that starts up the FHIR server which can be used for the process. An alternative would be to deploy a server just for this that the CI can connect to... depending on whichever makes more sense

Got it. So then yeah I think we need to reach out to SRE on this so that they can provision a validation server. Perhaps generically it should be an OpenSRP Terminology server that we can use to also provide our custom ones cc @dubdabasoduba @pld

**Comment by ndegwamartin** [comment]
This issue is blocked by (or will be fixed by) - https://github.com/onaio/fhir-tooling/issues/306

**Comment by Wambere** [comment]
No longer necessary since https://github.com/onaio/fhir-resources/pull/3589 was already closed
