### ISSUE TITLE
HAPI FHIR Validation Server setup and deployment

### ISSUE THREAD

**Issue by ndegwamartin** [onaio/fhir-tooling#306]
We need to have a running HAPI FHIR server in order to support validation. Our implementation requires a live server to be running - see https://github.com/onaio/fhir-tooling/issues/305

We could have the server deployed for the validation and maybe use the same server for terminologies as per the FHIR  spec ([Documentation on when to use a Terminology Service in FHIR](https://www.devdays.com/wp-content/uploads/2021/12/Jim-Steel-FHIR-Terminology-Service-APIs-DevDays-2019-Redmond.pdf))

**Factors to consider:**
1. **Specs of the server** - If the server is a validation server only we need less computing resources than a terminology server (for all projects)
2. **Server software versions** - We can deploy the latest JPA + HAPI FHIR Server or the current one we have in our deployments to be aligned to current production
3. **HAPI FHIR Modules** - We need to enable the _Clinical Reasoning module_ when deploying - [see CR flag deployment script ](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/3066622bd3fb6c1412b068e2de519047a11cefb5/src/main/resources/application.yaml#L85)

**Comment by Wambere** [comment]
One more thing, for the QuestionnaireResponse to be generated as expected we need to have cr enabled set to true

[ref link](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/3066622bd3fb6c1412b068e2de519047a11cefb5/src/main/resources/application.yaml#L85)

**Comment by pld** [comment]
is the other option to spin up a HAPI server in the CI flow, run tests against that, then spin it down, but problem w/this is that it'd be too slow?

**Comment by ndegwamartin** [comment]
> is the other option to spin up a HAPI server in the CI flow, run tests against that, then spin it down, but problem w/this is that it'd be too slow?

Should be feasible to implement but will be a higher LOE and C.I. will probably be slower when running the validation

**Comment by ndegwamartin** [comment]
**Here are the final steps based on the stated factors:**
1. We only need to focus on validation for now so a low spec server is fine
2. For the JPA + HAPI server lets use the latest - https://github.com/hapifhir/hapi-fhir-jpaserver-starter
3. The CR flag should be enabled as highlighted above - [Sample config here](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/3066622bd3fb6c1412b068e2de519047a11cefb5/src/main/resources/application.yaml#L85)
4. We can use the Google Gateway for auth - [Google FHIR Gateway 0.4.0](https://github.com/google/fhir-gateway/releases/tag/0.4.0) and [release artifacts here](https://central.sonatype.com/search?q=com.google.fhir.gateway) and [here (docker)](https://console.cloud.google.com/artifacts/docker/fhir-proxy-build/us/stable/fhir-gateway?project=fhir-proxy-build)
5. Gateway configurations are as on the main README - https://github.com/google/fhir-gateway

**Comment by ndegwamartin** [comment]
We can investigate whether it is feasible to whitelist requests from Github(C.I.) and then use that as the auth mechanism in which case we will not need the Keycloak and Gateway setups (thanks for this @pld ) 

cc @bennsimon @dubdabasoduba

**Comment by dubdabasoduba** [comment]
@ndegwamartin what are [these](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/3066622bd3fb6c1412b068e2de519047a11cefb5/src/main/resources/application.yaml#L217-L225) used for? If they are used somehow for validation do we need the server? I haven't checked so I might be sending you on a wild goose chase.

**Comment by ndegwamartin** [comment]
> @ndegwamartin what are [these](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/3066622bd3fb6c1412b068e2de519047a11cefb5/src/main/resources/application.yaml#L217-L225) used for? If they are used somehow for validation do we need the server? I haven't checked so I might be sending you on a wild goose chase.

That is a config on the server side, i.e HAPI itself . The above configures the url as logical identifiers - https://hapifhir.io/hapi-fhir/docs/server_jpa/configuration.html#logical-references

Note, our validation approach requires the server with or without that enabled since we use $populate operations for the QR generation cc @Wambere

**Comment by Wambere** [comment]
No longer necessary since https://github.com/onaio/fhir-resources/pull/3589 was already closed
