### ISSUE TITLE
Extend uploading/artifact management support in efsity

### ISSUE THREAD

**Issue by pld** [onaio/fhir-tooling#79]
Depends on/blocked by [v1](https://github.com/onaio/fhir-tooling/issues/29)

## Transaction support
Ideally when publishing the artifacts, all the individual upload POST requests should succeed or fail entirely for a run. This makes sense because we tag the resources on the server with the same version value.

The easiest way to achieve this would be to leverage BATCH posting to the HAPI FHIR server which supports transactions natively with Bundle type BATCH . See https://build.fhir.org/bundle.html 

## Properties Management
- In v1 one needs to pass an _Access token_ with the `--access-token` flag when running the script for authentication 
- Implementation of OAuth2 support for token management will add these properties 
   - CLIENT_ID 
   - CLIENT_SECRET
   - CLIENT_SCOPE

## Publishing state management
- For projects that do not follow the [recommended file structure documented here](https://docs.google.com/document/d/1Seoo9YYDBI87lmkA5siNqWsdYIgiwE_EYZ6relz8V14), we could have a map of non standard path folders to internally map the resource folders to custom locations
   - key - `file_structure_map`
   - value - json e.g. 
```json
   {
      "file_structure_map": { 
           "questionnaires" : "/my/custom/path/for/questionnaires" ,
           "plandefinitions" : "/my/custom/path/for/plandefinitions" 
       }
    }
```

**Notes**
- The keys in the `file_structure_map` json object correspond to folder names in the standardized structure convention see [Proposed FHIR Resources project structure here](https://docs.google.com/document/d/1Seoo9YYDBI87lmkA5siNqWsdYIgiwE_EYZ6relz8V14)

**Implementation Notes**
- The `.efsity` folder should always be versioned on Github _(i.e. under the fhir-resources repo project)_ 
- If the latest contents of the `.efsity` folder are not pushed, someone else can inadvertently overwrite those changes
- Properties can be provided via CLI or via the Dot Env file. CLI flags take precedence
- Time stamps to be in ISO 8601 format see https://www.iso.org/iso-8601-date-and-time-format.html

**Resources**
- https://build.fhir.org/bundle.html
- https://www.iso.org/iso-8601-date-and-time-format.html
- [Proposed FHIR Resources project structure](https://docs.google.com/document/d/1Seoo9YYDBI87lmkA5siNqWsdYIgiwE_EYZ6relz8V14)

**Comment by Wambere** [comment]
Completed by https://github.com/onaio/fhir-tooling/pull/111
