### ISSUE TITLE
Enhanced Efsity Validation on FHIR Resources Repo CI

### ISSUE THREAD

**Issue by ndegwamartin** [onaio/fhir-tooling#83]
Currently, we have **DefaultProfileValidation** integrated to the [fhir-resources](https://github.com/onaio/fhir-resources) repo continuous integration process. We need to add the (various) other types of validation that Efsity supports in order to catch any such issues early on.

Before that we need a conversation with the stakeholders _(Digital Health T/PMs)_ on which of the items listed in the [Efsity CI integration discussion here](https://github.com/onaio/fhir-resources/discussions/1363#discussioncomment-6219367) should be enforced as fatal errors _(Errors that must be fixed thus causing the CI build to fail)_

- [x] Facilitate Conversation + Decision making aforementioned with T/PMs
- [x] Integration to the FHIR Resources repository CI workflow
- [ ] Update on the #fhir channel once its live

**Comment by pld** [comment]
I think we ignore it

**Comment by ndegwamartin** [comment]
After a chat with @Wambere I think we should not reduct the validation scope. That refactor was done to speed up merging by only validating what the PR changed.

 I think the project teams should dedicate the time to fix, especially clean up all unused references in their configs once and for all. That way we don't need to refactor the validator and plus we end up with lean project configs.
