### ISSUE TITLE
Print Errors for config validation

### ISSUE THREAD

**Issue by Wambere** [onaio/fhir-tooling#94]
Currently the [config validation](https://github.com/onaio/fhir-tooling/pull/92) works like any regular JSON schema validation by throwing the error and exiting when it runs into an error. We need to modify this so that it is printing all the errors in the terminal like all the other efsity validating functions and only exiting  on completion. This will make it easier to see all the errors and fix them once instead of having to run and fix the issues one at a time

**Comment by ndegwamartin** [comment]
Closing this since PR is merged in here https://github.com/onaio/fhir-tooling/pull/99
